### ISSUE TITLE
LiveDNS supported/

### ISSUE THREAD

**Issue by petemcdonnell** [brianpcurran/gandi-automatic-dns#18]
Will this script still work after migrating to Gandi's LiveDNS?

**Comment by petemcdonnell** [comment]
To update this issue, no, gad does NOT work with the LiveDNS platform.  I've switched to: https://github.com/cavebeat/gandi-live-dns

**Comment by brianpcurran** [comment]
Thanks for testing this. As you found out, no, gad does not work with LiveDNS nor are there any plans currently to make it.

**Comment by brianpcurran** [comment]
To follow up on this issue, I just released [version 1.0.0](https://github.com/brianpcurran/gandi-automatic-dns/releases/tag/v1.0.0) of gad, which has v5/LiveDNS support. Let me know if you have any issues.
