### ISSUE TITLE
[FR] notify on new commits

### ISSUE THREAD

**Issue by laur89** [brianpcurran/gandi-automatic-dns#19]
Hi, I'm maintaining a [dockerised](https://github.com/laur89/docker-gandi-dns-update) version of this script, and discovered couple of days ago my domains were not being updated. Apparently change in Gandi API, and the repo was out sync with this one.

Long story short, could you please set up your repository to ping me a mail whenever a commit is pushed?

**Comment by PxxBxx** [comment]
@laur89 I will look forward your docker, but I have to remind you that Gandi alerted all clients some monthes ago. I went there to check for updates (pull is easier than push).
If you want to be alerted when a repository is updated (commit), subscribe/watch for it !

**Comment by brianpcurran** [comment]
You can subscribe to the Atom feed here if you want to get notifications: https://github.com/brianpcurran/gandi-automatic-dns/commits/master.atom

Found on this StackOverflow question: https://stackoverflow.com/questions/7353538/setting-up-an-github-commit-rss-feed
