### ISSUE TITLE
Created a new snapshot and tried to update the following live A records to [X.X.X.X]  with TTL of [XXX] seconds: @ 

### ISSUE THREAD

**Issue by e-yonder** [brianpcurran/gandi-automatic-dns#24]
I have been testing the gad script for 24 hours. However, it only creates a snapshot without changing the record chosen, namely @ here.
I am unsure as to what is going wrong. Using http://doc.livedns.gandi.net/ gandi liveDNS API, I created a zone file and I got my zone uuid. I have noticed that once I started using gad, this uuid had changed.
Another hypothesis, it that my zone file is misconfigured.
If there is any hint as to what I did wrong, your help would be appreciated.

**Comment by brianpcurran** [comment]
Interesting. Can you run gad as you normally do, but add the `-e` flag? That should generate a bunch of debugging output will be helpful. Feel free to obfuscate domain name, IP address, etc. if you want to.

**Comment by e-yonder** [comment]
Thank you.
Here is the debugging output, after running:
`sudo ./gad -5 -f -e -v -a $APIKEY -d mywebsite.xyz -r "@"`
> Initial variables:
> ---
> apikey = $APIKEY
> domain = mywebsite.xyz
> records = @
> ttl (only relevant with LiveDNS) = 
> record_type = A
> ip_regex = \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)
> ---
> 
> IP information:
> ---
> ext_ip_method: OpenDNS
> ext_ip: X.X.X.X
> ---
> 
> REST call to endpoint:
> ---
> domains/mywebsite.xyz
> ---
> 
> Sending REST message tmp_message:
> ---
> GET /api/v5/domains/mywebsite.xyz HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.0
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> zone_id:
> ---
> $ZoneID
> ---
> 
> REST call to endpoint:
> ---
> zones/$ZoneID/records/@/A
> ---
> 
> Sending REST message tmp_message:
> ---
> GET /api/v5/zones/$ZoneID/records/@/A HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.0
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> Results after checking record:
> ---
> record: @
> record_value: 127.0.0.1
> records_to_create: 
> records_to_update: @
> ---
> 
> REST call to endpoint:
> ---
> /zones/$ZoneID/snapshots
> ---
> 
> Sending REST message tmp_message:
> ---
> POST /api/v5//zones/$ZoneID/snapshots HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.0
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> new_snapshot_id:
> ---
> $SnapSHOT_ID
> ---
> 
> REST call to endpoint:
> ---
> /zones/$ZoneID/records/@/A
> ---
> 
> Sending REST message tmp_message:
> ---
> PUT /api/v5//zones/$ZoneID/records/@/A HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.0
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 54
> X-Api-Key: $APIKEY
> 
> {"rrset_ttl"; "300", "rrset_values": ["X.X.X.X"]}
> ---
> 
> new_record_message:
> ---
> 
> ---
> 
> Created a new snapshot and tried to update the following live A records to X.X.X.X with TTL of 300 seconds: @

**Comment by brianpcurran** [comment]
Could you try the latest version from the master branch? I removed some extraneous slashes that were in some of the rest commands. (You can see these extra slashes in the lines like `POST /api/v5//zones/$ZoneID/snapshots HTTP/1.1`.)

**Comment by e-yonder** [comment]
Nothing has changed: the update is not being performed.
Running the following:
`./gad -5 -f -e -v -a $APIKEY -d MY_WEBSITE -r "@"`

> Initial variables:
> ---
> apikey = $APIKEY
> domain = MY_WEBSITE
> records = @
> ttl (only relevant with LiveDNS) = 
> record_type = A
> ip_regex = \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)
> ---
> 
> IP information:
> ---
> ext_ip_method: OpenDNS
> ext_ip: X.X.X.X
> ---
> 
> REST call to endpoint:
> ---
> domains/MY_WEBSITE
> ---
> 
> Sending REST message tmp_message:
> ---
> GET /api/v5/domains/MY_WEBSITE HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.1
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> zone_id:
> ---
> $Zone_ID
> ---
> 
> REST call to endpoint:
> ---
> zones/$Zone_ID/records/@/A
> ---
> 
> Sending REST message tmp_message:
> ---
> GET /api/v5/zones/$Zone_ID/records/@/A HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.1
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> Results after checking record:
> ---
> record: @
> record_value: 127.0.0.1
> records_to_create: 
> records_to_update: @
> ---
> 
> REST call to endpoint:
> ---
> zones/$Zone_ID/snapshots
> ---
> 
> Sending REST message tmp_message:
> ---
> POST /api/v5/zones/$Zone_ID/snapshots HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.1
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 0
> X-Api-Key: $APIKEY
> 
> 
> ---
> 
> new_snapshot_id:
> ---
> $New_SNAPSHOT_ID
> ---
> 
> REST call to endpoint:
> ---
> zones/$Zone_ID/records/@/A
> ---
> 
> Sending REST message tmp_message:
> ---
> PUT /api/v5/zones/$Zone_ID/records/@/A HTTP/1.1
> User-Agent: Gandi Automatic DNS shell script/1.2.1
> Host: dns.api.gandi.net
> Content-Type: application/json
> Content-Length: 54
> X-Api-Key: $APIKEY
> 
> {"rrset_ttl"; "300", "rrset_values": ["X.X.X.X"]}
> ---
> 
> new_record_message:
> ---
> 
> ---
> 
> Created a new snapshot and tried to update the following live A records to X.X.X.X with TTL of 300 seconds: @

**Comment by brianpcurran** [comment]
This was a really silly typo (semicolon instead of colon) so the update() function wasn't sending valid JSON. Should be fixed in [release 1.2.1](https://github.com/brianpcurran/gandi-automatic-dns/releases/tag/v.1.2.1). Thanks for catching this! Let me know if it starts working now and I'll close this out.

**Comment by e-yonder** [comment]
THANK YOU so much for your work!
The update works now!!!!
This is so great.

**Comment by brianpcurran** [comment]
Great!! 🙂I would have been very confused one day when my IP address wasn't up to date and would have had to track down this bug, so I appreciate you reporting it!
