### ISSUE TITLE
Thanks for this! Also, some notes from a packager.

### ISSUE THREAD

**Issue by majewsky** [brianpcurran/gandi-automatic-dns#25]
Hi, just wanted to stop by to thank you for making this! I just had to migrate away from https://github.com/jasontbradshaw/gandi-dyndns because of the v5 API change, and `gad` worked very well for me.

Since I like to have everything in packages, I packaged this for Arch Linux at https://aur.archlinux.org/packages/gandi-automatic-dns/ - If you like, you can add that link to the README.

One note from a packaging perspective: It would be nice if you also put the license in the repo as a separate file. Packaging rules usually require the license to be included in the package as a separate file. As you can see in [line 19 of my PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gandi-automatic-dns#n19), I used some sed magic to extract the license from the code, but that may easily break between upgrades.

**Comment by brianpcurran** [comment]
I'm glad gad has been helpful to you with the new v5 API! I just tagged [release 1.3.3](https://github.com/brianpcurran/gandi-automatic-dns/releases/tag/v1.3.3-1), with the license info included in a separate file (`LICENSE`) and a link to the Arch Linux package (with some more detailed install and crontab setup instructions too). I'll go ahead and close this out.

**Comment by brianpcurran** [comment]
PS - I like your blog! The posts about API design in Go, terminal latency, and RPM file format were particularly interesting.

**Comment by majewsky** [comment]
Thanks! If, by any chance, you're at 35C3 right now, we can meet for a drink or something. If you're there, call me on DECT 5169.

**Comment by brianpcurran** [comment]
Unfortunately I'm not, but thanks for the invite!
