### ISSUE TITLE
[Suggestion] Systemd .timer

### ISSUE THREAD

**Issue by thisischrys** [brianpcurran/gandi-automatic-dns#26]
Any chance of a systemd timer? I could make a pull request if you'd accept it?

**Comment by brianpcurran** [comment]
How complex/large would this be? I'm not super familiar with systemd. If it's something short or equivalent to a crontab entry I'd consider adding it to the README.

**Comment by brianpcurran** [comment]
I'm going to close this out due to lack of response.
