### ISSUE TITLE
Failed to determine external IP address with OpenDNS.

### ISSUE THREAD

**Issue by e-yonder** [brianpcurran/gandi-automatic-dns#27]
Hello,
I haven't been using gad for a few months, being busy with other stuff.
In my subject line, I have indicated the error message I get 'Failed to determine external IP address with OpenDNS'

I have also found this in a previous issue that was closed: 

> Alternately, if OpenDNS isn't working for you for some reason, you could try using the -s flag and piping "curl ipinfo.io/ip" to your gad command.

I am at loss as to how 'piping "curl ipinfo.io/ip" is done. What syntax should I use in the command line with gad?
Regards,
Christophe

**Comment by brianpcurran** [comment]
Hi. Were you able to figure this out? If you want to pipe your IP address on stdout, just add the `-s` flag to your `gad` command. There's an example in the README.

**Comment by sven337** [comment]
I am observing that problem too - I need dig -4 otherwise it makes an IPv6 request and opendns returns nothing for the A record.

So, for IPv4, you need dig -4 A, and for IPv6, dig -6 AAAA

**Comment by brianpcurran** [comment]
Should be fixed by https://github.com/brianpcurran/gandi-automatic-dns/pull/29

Released as v1.4.1: https://github.com/brianpcurran/gandi-automatic-dns/releases/tag/v1.4.1
