### ISSUE TITLE
release tag format

### ISSUE THREAD

**Issue by majewsky** [brianpcurran/gandi-automatic-dns#28]
Is there a particular reason why the `v1.3.3` tag was replaced by `v1.3.3-1`? This broke the build of the AUR package in surprising ways.

**Comment by brianpcurran** [comment]
Good question! I honestly forget at this point. I just republished 1.3.3 with the proper v1.3.3 tag, sorry for the package breakage. Let me know if this resolves things.

**Comment by majewsky** [comment]
Yes, looks good now. Thanks.
