### ISSUE TITLE
invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by auxym** [brianpcurran/gandi-automatic-dns#4]
I try to run the run with the basic syntax `tools/gandi-automatic-dns/gad -a <key> -d <domain> -r "record". The full output follows. The zone file is not updated with my ip.

```
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
Activating version 1 of the zonefile for domain ncis.onl...
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify error:num=19:self signed certificate in certificate chain
verify return:0
HTTP/1.1 200 OK
Date: Fri, 21 Nov 2014 03:34:45 GMT
Server: Apache/2.2.16 (Debian) mod_ssl/2.2.16 OpenSSL/0.9.8o mod_wsgi/3.3 Python/2.6.6
Content-Length: 334
Vary: Accept-Encoding
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version='1.0'?>
<methodResponse>
<fault>
<value><struct>
<member>
<name>faultCode</name>
<value><int>1</int></value>
</member>
<member>
<name>faultString</name>
<value><string>&lt;type 'exceptions.ValueError'&gt;:invalid literal for int() with base 10: ''</string></value>
</member>
</struct></value>
</fault>
</methodResponse>
Tried to update the following A records to 192.222.178.237:  home\nThere is no error checking on the RPCs so check the web interface if you want to be sure the update was successful, or look at the methodResponse from domain.zone.version.set() (a response of 1 means success).
```

**Comment by brianpcurran** [comment]
@auxym, if you are still having this issue please let me know. Also try the latest commit and use the -e option for debugging output.

**Comment by jonkeane** [comment]
I'm getting the same error. I have not yet activated the production API for gandi, but this should work on the testing side as well, no? I used the -e option, and here is the output:

~/bin/gandi-automatic-dns$ ./gad -e -a [apikey] -d [domain] -r A
Initial flags:

apikey = [apikey]
domain = [domain]
records = A
record_type = A
ip_regex = \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)

IP information:

ext_ip_method = OpenDNS
ext_ip = 24.136.4.31

RPC call to methodName = domain.info

Sending XML-RPC message tmp_message =

POST /xmlrpc/ HTTP/1.0
User-Agent: Gandi Automatic DNS shell script/0.3
Host: rpc.gandi.net:443
Content-Type: text/xml
Content-Length: 271

<?xml version="1.0"?>
<methodCall>
  <methodName>domain.info</methodName>
  <params>
    <param>
      <value><string>[apikey]</string></value>
    </param>
    <param>
      <value><string>[domain]</string></value>
    </param>
  </params>
</methodCall>

zone_id = 

RPC call to methodName = domain.zone.record.list

Sending XML-RPC message tmp_message =

POST /xmlrpc/ HTTP/1.0
User-Agent: Gandi Automatic DNS shell script/0.3
Host: rpc.gandi.net:443
Content-Type: text/xml
Content-Length: 646

<?xml version="1.0"?>
<methodCall>
  <methodName>domain.zone.record.list</methodName>
  <params>
    <param>
      <value><string>[apikey]</string></value>
    </param>
    <param>
      <value><int></int></value>
    </param>
    <param>
      <value><int>0</int></value>
    </param>
    <param>
      <value>
        <struct>
          <member>
            <name>name</name>
            <value><string>A</string></value>
          </member>
          <member>
            <name>type</name>
            <value><string>A</string></value>
          </member>
        </struct>
      </value>
    </param>
  </params>
</methodCall>

record = A
record_value = 
records_to_create = A
records_to_update = 

RPC call to methodName = domain.zone.version.new

Sending XML-RPC message tmp_message =

POST /xmlrpc/ HTTP/1.0
User-Agent: Gandi Automatic DNS shell script/0.3
Host: rpc.gandi.net:443
Content-Type: text/xml
Content-Length: 268

<?xml version="1.0"?>
<methodCall>
  <methodName>domain.zone.version.new</methodName>
  <params>
    <param>
      <value><string>[apikey]</string></value>
    </param>
    <param>
      <value><int></int></value>
    </param>
  </params>
</methodCall>

new_version_id = 1

RPC call to methodName = domain.zone.record.add

Sending XML-RPC message tmp_message =

POST /xmlrpc/ HTTP/1.0
User-Agent: Gandi Automatic DNS shell script/0.3
Host: rpc.gandi.net:443
Content-Type: text/xml
Content-Length: 771

<?xml version="1.0"?>
<methodCall>
  <methodName>domain.zone.record.add</methodName>
  <params>
    <param>
      <value><string>[apikey]</string></value>
    </param>
    <param>
      <value><int></int></value>
    </param>
    <param>
      <value><int>1</int></value>
    </param>
    <param>
      <value>
        <struct>
          <member>
            <name>name</name>
            <value><string>A</string></value>
          </member>
          <member>
            <name>type</name>
            <value><string>A</string></value>
          </member>
          <member>
            <name>value</name>
            <value><string>24.136.4.31</string></value>
          </member>
        </struct>
      </value>
    </param>
  </params>
</methodCall>

HTTP/1.1 200 OK
Date: Wed, 11 Mar 2015 03:23:28 GMT
Server: Apache/2.2.16 (Debian) mod_ssl/2.2.16 OpenSSL/0.9.8o mod_wsgi/3.3 Python/2.6.6
Content-Length: 334
Vary: Accept-Encoding
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version='1.0'?>
<methodResponse>
<fault>
<value><struct>
<member>
<name>faultCode</name>
<value><int>1</int></value>
</member>
<member>
<name>faultString</name>
<value><string>&lt;type 'exceptions.ValueError'&gt;:invalid literal for int() with base 10: ''</string></value>
</member>
</struct></value>
</fault>
</methodResponse>
Activating version 1 of the zonefile for domain [domain]...

openssl s_client output and domain.zone.version.set() method response:

RPC call to methodName = domain.zone.version.set

Sending XML-RPC message tmp_message =

POST /xmlrpc/ HTTP/1.0
User-Agent: Gandi Automatic DNS shell script/0.3
Host: rpc.gandi.net:443
Content-Type: text/xml
Content-Length: 327

<?xml version="1.0"?>
<methodCall>
  <methodName>domain.zone.version.set</methodName>
  <params>
    <param>
      <value><string>[apikey]</string></value>
    </param>
    <param>
      <value><int></int></value>
    </param>
    <param>
      <value><int>1</int></value>
    </param>
  </params>
</methodCall>

HTTP/1.1 200 OK
Date: Wed, 11 Mar 2015 03:23:28 GMT
Server: Apache/2.2.16 (Debian) mod_ssl/2.2.16 OpenSSL/0.9.8o mod_wsgi/3.3 Python/2.6.6
Content-Length: 334
Vary: Accept-Encoding
Connection: close
Content-Type: text/xml; charset=utf-8

<?xml version='1.0'?>
<methodResponse>
<fault>
<value><struct>
<member>
<name>faultCode</name>
<value><int>1</int></value>
</member>
<member>
<name>faultString</name>
<value><string>&lt;type 'exceptions.ValueError'&gt;:invalid literal for int() with base 10: ''</string></value>
</member>
</struct></value>
</fault>
</methodResponse>

Tried to update the following A records to 24.136.4.31:  A

There is no error checking on the RPCs so check the web interface if you want to be sure the update was successful, or look at the methodResponse from domain.zone.version.set() above (a response of 1 means success).

**Comment by brianpcurran** [comment]
I just tested with the test API and get the same behavior. It looks like the domain.info function of the API doesn't return a zone ID on the testing platform, so this is expected. I added a check for this in the latest version of the script that advises of an empty zone_id and suggests using gad's -t flag with the production API key.
